services:
  front-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ./.env.development
    command:
      [
        "sh",
        "-c",
        "yarn install && yarn global add pm2@5.4.2 && pm2 start ecosystem.config.js --only FRONT-DEV --log-date-format 'DD-MM HH:mm:ss.SSS' && tail -f /dev/null",
      ]
    ports:
      - "3102:3102" # Maps container port 3102 to localhost port 3102
